# Generated by Django 4.2.13 on 2024-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BluetoothData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("card_number", models.CharField(max_length=8)),
                ("status", models.CharField(max_length=1)),
            ],
        ),
    ]
