# Generated by Django 4.2.13 on 2024-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysqlExp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bluetoothdata",
            name="card_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bluetoothdata",
            name="status",
            field=models.CharField(max_length=10),
        ),
    ]
