# Generated by Django 4.2.13 on 2024-07-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysqlExp", "0002_alter_bluetoothdata_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bluetoothdata",
            name="card_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bluetoothdata",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
