# Generated by Django 4.2.13 on 2024-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysqlExp", "0003_alter_bluetoothdata_card_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
