# Generated by Django 4.2.13 on 2024-07-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysqlExp", "0004_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
